# Site settings
title: Yuhj's Blog
email: lin5667181@163.com
description: "Android,Java Leaning"
permalink: /:year/:month/:day/:title.html
baseurl: ""
url: "http://yuh.blog.com"
atom-baseurl: "http://yuhj.blog.com"
author: "yuhj"

# Build settings
# permalink: date

highlighter: rouge
markdown: kramdown
kramdown:
  input:          GFM
  auto_ids:       true
  auto_id_prefix: 'id-'

#duoshuo
  comments :
    provider : duoshuo
    duoshuo :
      short_name : smallsoho

navigations:
  - title: About
    class: fa fa-list-ul
    href: /about/
  - title: Archive
    class: fa fa-tags
    href: /archive/
  - title: Categories
    class: fa fa-user
    href: /categories/
  - title: Tags
    class: fa fa-film
    href: /tags/
  - title: Rss
    class: fa fa-rss
    href: /atom.xml
